### ISSUE TITLE
Trouble in installing

### ISSUE THREAD

**Issue by Zhentao-Liu** [jannessm/quadric-mesh-simplification#15]
I'm sorry that I have trouble in installing your package. When I use pip install quad_mesh_simplify, it only install a dist-info folder. When I download the repository, and run the command that your provide, It just fails. What's wrong?

**Comment by Zhentao-Liu** [comment]
![install](https://user-images.githubusercontent.com/81148025/185034484-f07c4b1a-d3c0-4687-898f-17a20d508294.png)
When I run pip install . , it shows that successfully installed quad-mesh-simplify-1.1.5, but I don't know where it installed?

**Comment by Zhentao-Liu** [comment]
Ok, I find that it install in my envs site-package named as quad_mesh_simplify-1.1.5.dist-info, but there is still no file named simplify_mesh.py. I think I failed in installing this package. Who can solve my problem.

**Comment by Arnout25** [comment]
had the same problem, just download the zip and put quad_mesh_simplify in your site-packages by hand

**Comment by ntakouris** [comment]
```
cp -r quadric-mesh-simplification/quad_mesh_simplify/ /opt/conda/lib/python3.x/site-packages/quad_mesh_simplify
```
