### ISSUE TITLE
Maximum error

### ISSUE THREAD

**Issue by FreakTheMighty** [jannessm/quadric-mesh-simplification#3]
It would be great to support a maximum error parameter. Ideally we can say, “decimate this mesh to n faces, but don’t remove any faces then produce error greater than x threshold.” 

This would allow a more aggressive face target, while maintaining a particular level of quality.

**Comment by jannessm** [comment]
Hey. This is a great feature. Due to the application of my implementation, I was focussing on the node reduction, only ;).
