### ISSUE TITLE
Four faced quad

### ISSUE THREAD

**Issue by FreakTheMighty** [jannessm/quadric-mesh-simplification#6]
I don't think this is bug, but I thought I'd pose the question here.

When I decimate a very thin piece of geometry sometimes I find quads, 4 vertices, that have 4 faces instead of 2. The result is a lot of z-fighting in my final application. I've been trying to figure out if this is something I could to clean up as a post process, but can't quite figure out a general way to describe the issue never mind an algorithm for cleaning it up.

Do you think this is something that could be improved in the decimation algorithm? Any other thoughts about how to approach the issue?

![image](https://user-images.githubusercontent.com/247092/91865708-4993c980-ec37-11ea-89f7-fd449c1b2798.png)

**Comment by jannessm** [comment]
This is indeed not part of the implemented algorithm. But for your problem: maybe you can start with one face and remove all overlapping faces. You should easily get a solution for this from google ;).

I will close this issue, since it is no issue of the provided algorithm.
